# Generated by Django 2.0.6 on 2018-08-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_producto_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colores',
        ),
        migrations.DeleteModel(
            name='Materiales',
        ),
    ]
